/*------------------------
* �ü�_M_����
*-------------------------
*/
DROP TABLE TB_PR_M_INFO;
 CREATE TABLE TB_PR_M_INFO 
(
	TR_GBN	    VARCHAR(2)		NOT NULL ,
	BJD_CODE	VARCHAR(10)     NOT NULL ,
	JIBUN	    VARCHAR(20)      NOT NULL ,
	KAPT_NAME	VARCHAR(200)    NOT NULL ,
	AREA_UNIT	NUMBER(10,2)    NOT NULL ,
	TR_AMT	    NUMBER(20)      NULL ,
	DEPOSIT_AMT	NUMBER(20)      NULL ,
	RENT_AMT	NUMBER(20)      NULL ,
	BAT_YM	    VARCHAR(6)      NOT NULL ,
    WK_GBN       VARCHAR(2)     NOT NULL ,
    CONTRACT_YMD VARCHAR(8)     NOT NULL ,
	MOD_USER    VARCHAR(10)	    NULL ,
	MOD_DATE	DATE DEFAULT    SYSDATE    
);

ALTER TABLE TB_PR_M_INFO ADD CONSTRAINT  TB_PR_M_INFO PRIMARY KEY (TR_GBN, BJD_CODE, JIBUN, KAPT_NAME, AREA_UNIT)  ;
COMMENT ON TABLE TB_PR_M_INFO      IS '�ü�_M_����';
COMMENT ON COLUMN TB_PR_M_INFO.TR_GBN       IS '�ŷ�����(1.����Ʈ / 2.���ǽ���)';
COMMENT ON COLUMN TB_PR_M_INFO.BJD_CODE     IS '�������ڵ�';
COMMENT ON COLUMN TB_PR_M_INFO.JIBUN         IS '����';
COMMENT ON COLUMN TB_PR_M_INFO.KAPT_NAME 	 IS '������';
COMMENT ON COLUMN TB_PR_M_INFO.TR_AMT       IS '�ŸŰŷ��ݾ�(����:����)';
COMMENT ON COLUMN TB_PR_M_INFO.DEPOSIT_AMT  IS '������(����:����)';
COMMENT ON COLUMN TB_PR_M_INFO.RENT_AMT     IS '����';
COMMENT ON COLUMN TB_PR_M_INFO.AREA_UNIT    IS '����';
COMMENT ON COLUMN TB_PR_M_INFO.BAT_YM       IS '��ġ��ȸ���';
COMMENT ON COLUMN TB_PR_M_INFO.WK_GBN       IS '�۾�����-11.����Ʈ �Ÿ�,12.����Ʈ ������,21.���ǽ� �Ÿ�, 22���ǽ� ������';
COMMENT ON COLUMN TB_PR_M_INFO.CONTRACT_YMD IS '�����(�ֱٰ����)';
COMMENT ON COLUMN TB_PR_M_INFO.MOD_USER     IS '������'; 
COMMENT ON COLUMN TB_PR_M_INFO.MOD_DATE     IS '�����Ͻ�'; 